### ISSUE TITLE
[Bug] Beta Builds Crash

### ISSUE THREAD

**Issue by GazbonicAcid** [cyanobacterium/BaseMetals#82]
[ATLauncher Console Log](https://hastebin.com/kokohekibu.md)
[Logs.zip](https://github.com/cyanobacterium/BaseMetals/files/663803/Logs.zip)
ModernMetals-1.10.2-0.12.9-beta1.jar 2016-Dec-19
BaseMetals-1.10.2-2.5.0-beta1.jar 2016-Dec-19
Crash seems to be because they are looking for vanilla lava as a molten fluid.
I am already running the latest forge 2185 for 1.10.2

**Comment by jriwanek** [comment]
Try grabbing the jars from maven again, should work now.

**Comment by GazbonicAcid** [comment]
Still crashing.
Now it's giving a "No Def Class Found" from the tinker's construct plugin in modern metals.
[ATLauncher Console Log](https://hastebin.com/curobiquga.md)
[Logs Again.zip](https://github.com/cyanobacterium/BaseMetals/files/665079/Logs.Again.zip)
Edit: though the "lava not found" crash was fixed.

**Comment by GazbonicAcid** [comment]
After removing the modern metals dev build,
game loads and I can get in.

**Comment by jriwanek** [comment]
I still need to push an update for the modernmetals dev build

**Comment by GazbonicAcid** [comment]
[ATLauncher Console Again](https://hastebin.com/cucutarinu.md)
[Logs Again.zip](https://github.com/cyanobacterium/BaseMetals/files/666780/Logs.Again.zip)
The excerpt to look at....

[21/12/2016 09:58:23 AM] java.lang.NoSuchMethodError: modernmetals.init.VillagerTrades.registerCommonTrades()V

Edit: At least getting these issues squashed in the dev build means an easier time squashing bugs from release...I hope.

**Comment by jriwanek** [comment]
Use new issuetracker for all new reports:
https://github.com/MinecraftModDevelopment/BaseMetals/issues
